version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  psqldock:
    image: luisvid/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: brocal
      POSTGRES_USER: postgres
      POSTGRES_DB: ydiyoi
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-tier
  api:
    image: luisvid/ydi-yoi
    restart: always
    environment:
      # Local  host:'localhost' port:5434
      # Deploy host:'psqldock'  port:5432
      DB_DATABASE: ydiyoi
      DB_HOST: psqldock
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: brocal
      APPLICATION_URL: http://localhost:3000
    ports:
      - "3000:3000"
    networks:
      - app-tier
    depends_on:
      - psqldock
    links:
      - psqldock
      - smtp
  front:
    image: luisvid/ydiyoi-front
    restart: always
    ports:
      - "80:80"
    networks:
      - app-tier
    depends_on:
      - api
    links:
      - api
  smtp:
    image: registry.gitlab.com/ix.ai/smtp
    container_name: smtp
    restart: always
    ports:
      - "25:25"
    environment:
    # # To act as a Gmail relay
    # - GMAIL_USER=
    # - GMAIL_PASSWORD=
    # Generic SMTP Relay: ferozo
      - SMARTHOST_ADDRESS=c2090663.ferozo.com
      - SMARTHOST_PORT=465
      - SMARTHOST_USER=luis@agilmentor.com
      - SMARTHOST_PASSWORD=Brocal*5813
      - SMARTHOST_ALIASES=*.ferozo.com
    networks:
      - app-tier
