---
fullnameOverride: api-prod

replicaCount: 1

maxSurge: 40%
maxUnavailable: 40%

port: 4000

envs:
  - name: DB_DATABASE
    value: "ydiyoi"
  - name: DB_HOST
    value: '10.245.167.252'
  - name: DB_PORT
    value: "5432"
  - name: DB_PASSWORD
    value: ""
  - name: APPLICATION_URL
    value: "https://nft.openvino.org"
  - name: DB_USER
    value: postgres



image:
  repository: luisvid/ydi-yoi
  tag: 9
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

liveness:
  enabled: 1
  path: "/ping"

readiness:
  enabled: 1
  path: "/ping"

nginx:
  image:
    tag: 1.15-alpine
  config:
    file: nginx.conf
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.openvino.org
      paths:
      - /
  tls:
   - secretName: api-production-tls
     hosts:
       - api.openvino.org

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 126Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 9
  cpu:
    enabled: true
    targetPercentage: 80
  memory:
    enabled: true
    targetPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
